server:
  port: 8092

spring:
  rabbitmq:
    password: guest
    host: 47.101.33.159
    username: guest
    port: 5672
  application:
    name: CONFIGCLIENT
  cloud:
    consul:
      host: localhost
      port: 8500
  profiles:
    active: dev
